### ISSUE TITLE
create questionnaire

### ISSUE THREAD

**Issue by NicoDiePlume** [AlexHartveld/otree-costs-of-control-questionnaire-mturk#8]

**Comment by AlexHartveld** [comment]
Explanation page: Instructions for start-up.
Page 1: Demographic questions.
Options page 2
- Vignette 1-5 randomly on one page. 
**- Five pages in random order. Constant Vignette in HTML, Condition is part of the answer form -> 1A 1B 1C 1D.** 
Page 3: A thank-you and payment info page

Randomise questions on player-level: 
- 5 questions' order (random.shuffle())
- which of the 4 conditions for each question (random.choice())

### TODO's

- [x] Create basic set-up with 7 pages (intro + 5 pages + outro)
- [x] Create response option model 
- [x] Create the vignette pages with questions and random condition choice 
- [x] Design the shuffle function that randomises order of 5 pages
- [x] Design a better HTML page
- [ ] Add a progress bar
- [ ] Write proper intro and outro with Java

Inspiration: https://github.com/victorvanpelt/otree-questionnaire/blob/master/models.py
